version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brazil_news
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/brazil_news"
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  postgres_data:
